### ISSUE TITLE
[Feature request] Ability to edit giveaways

### ISSUE THREAD

**Issue by KimPlayz4LK** [jagrosh/GiveawayBot#100]
Hi! I would like to have the ability to edit giveaways, like i misspelled or forgot to add something, and there is no way to edit it.
Example: g!edit <mesage id of the giveaway> <thing to edit, like name or winner count> <value>
Example: g!edit 1234567890 name 100$ dollars

**Comment by KimPlayz4LK** [comment]
My issue number is #100, i hope you will add this 100% lol

**Comment by KimPlayz4LK** [comment]
Oh actually nevermind
Sorry haven't checked for existing suggestions #58

**Comment by jagrosh** [comment]
Duplicate of #58
