### ISSUE TITLE
New command

### ISSUE THREAD

**Issue by TnTN3Rd** [jagrosh/GiveawayBot#109]
A command were you can set a role to have a higher chance of winning so If you want people with the role vip to have a higher winning change then you can make it so they have a x% higher chance of winning

**Comment by quick007** [comment]
![image](https://user-images.githubusercontent.com/69743171/133947727-a4a3e3d6-4a11-4515-b582-01b9e93086f7.png)
(partially why you always hear with giveaways like "you don't need to pay money to enter", its not like Mcdonalds is a charity)
