### ISSUE TITLE
New commands 

### ISSUE THREAD

**Issue by TnTN3Rd** [jagrosh/GiveawayBot#110]
Add commands where you are able to add or remove Time from giveaways by doing !gremove/add <amount of time added or removed> <giveaway ID> for me this will be really helpful and hopefully a lot of others as well

**Comment by Sanduhr32** [comment]
This most likely won't be added as this could be abused heavily.
Do the math properly when calculating the time a giveaway should end.
`g!end` already allows you to end a giveaway early.
