### ISSUE TITLE
Create rule section 

### ISSUE THREAD

**Issue by MRJ-Badshah** [jagrosh/GiveawayBot#111]
Create a rule like you must have to send 10message you have do something you have invite people like this type @jagrosh

**Comment by jagrosh** [comment]
You can simply write a message above your giveaways explaining what your rules are, and then re-roll the giveaway if the person who won did not meet the requirements. This cannot be added into the bot, as limiting giveaways in this manner breaks the ToS.

**Comment by MRJ-Badshah** [comment]
Ok
