### ISSUE TITLE
Lost my Premium

### ISSUE THREAD

**Issue by MVNLive** [jagrosh/GiveawayBot#117]
Ive lost my Premium when i left your discord server. How can i get my premium back?

**Comment by MVNLive** [comment]
Im already back on your discord

**Comment by bup0441** [comment]
Try relinking your Patreon and Discord accounts so the Patreon bot gives you your role back, if that doesn't work cancel and then renew your pledge

**Comment by MVNLive** [comment]
Thanks.. worked...
