### ISSUE TITLE
[Feature Request] Reroll multiple times in one command

### ISSUE THREAD

**Issue by Bippetybob192** [jagrosh/GiveawayBot#119]
I am trying to reroll multiple winners from a giveaway because it has 10 winners and is irritating to do 1 by 1. but I cat find a way to rerollall or multiple winners in 1 command. is there a feature like this or wil it ever be added? thanks for your consideration and reading.

**Comment by jagrosh** [comment]
The `/greroll` command supports an argument for a number of rerolls.
