### ISSUE TITLE
Reroll

### ISSUE THREAD

**Issue by freekill101** [jagrosh/GiveawayBot#12]
So when I giveaway multiple things certain giveaways get overlapped, and since we don't want 1 person to get multiple items we need to reroll the extras but we can't. It just says "That is not a valid message ID" when we try to reroll a specific item. Whether we use the name, the name in "'s, in [ ], the @person the persons name as the ID nothing. So how do you reroll specific items??? @jagrosh

**Comment by jagrosh** [comment]
The issue tracker is only for bugs and feature requests. For support with the bot, please join the [support server](https://invite.gg/giveaways).
