### ISSUE TITLE
Giveaway won't end

### ISSUE THREAD

**Issue by thompson-ele** [jagrosh/GiveawayBot#122]
The giveaway didn't select winners when the time ran out and I tried using `!gend` but nothing is working
<img width="461" alt="Screen Shot 2021-12-20 at 9 34 17 AM" src="https://user-images.githubusercontent.com/12629117/146808690-4b8ac363-1ca5-4233-9cbe-2eb3ecbca213.png">

**Comment by TermosEs** [comment]
Same here.
![Screenshot_2021-12-21-01-01-05-37](https://user-images.githubusercontent.com/83133991/146813064-0b558a3f-e2da-4351-b609-499f9ebe78e7.png)

`!glist` there's active giveaway
![Screenshot_2021-12-21-01-08-41-35](https://user-images.githubusercontent.com/83133991/146812959-55678665-a251-4113-b85b-e7679e8c9525.png)

`!gend` & `!greroll` couldn't find recent giveaway
`!gend <msg id>` couldn't find msg id

**Comment by ajvxxi** [comment]
![image](https://user-images.githubusercontent.com/96445468/146826832-8d48e75b-3ab6-4b8f-b767-d769e3db7de6.png)

yeah its not working here either. I tried using !gend as well and nothing.

**Comment by msharris** [comment]
`!gend` and `!gend <id>` also not working for me.
`!glist` is working correctly and shows the active giveaway

**Comment by Melinezz** [comment]
Same for my server, thought we had just done so many giveaways we broke it.....

**Comment by Melinezz** [comment]
I can reroll the ones that are stuck, but they don't disappear, still show in the list.
