### ISSUE TITLE
Giveaway bot down

### ISSUE THREAD

**Issue by Bren8ross** [jagrosh/GiveawayBot#125]
The giveaway bot is down In my server

**Comment by jdbdndnxj** [comment]
Same here

**Comment by jdbdndnxj** [comment]
Nvm, bots back up for me!

**Comment by BadBatchNewBatch** [comment]
It’s currently down for me

**Comment by Domxnvk** [comment]
> It’s currently down for me

Is this a feature request or bug report? I don't think that GitHub is the right place to report downtime of the bot, the owner will know about this...
