### ISSUE TITLE
[Feature Request] Requirements to enter a giveaway (Requires X Y Z roles)

### ISSUE THREAD

**Issue by Blizzard2875** [jagrosh/GiveawayBot#133]
When using the g!create command the bot could ask for role requirements of the roles that are needed to enter the giveaway (multiple roles supported)

**Comment by Sanduhr32** [comment]
Please check the closed issues with similar suggestions for why this won't happen.

**Comment by jagrosh** [comment]
This is already possible. Make a channel that only those roles can see and host the giveaway in there.
