### ISSUE TITLE
[Feature Request] Allow us to change the amount of winners before giveaway ends

### ISSUE THREAD

**Issue by Yilmaz4** [jagrosh/GiveawayBot#135]
A command like `!gedit [message id]` which would allow us to change the amount of winners or change the title in case any spelling mistake was made would be great in servers with lots of people, as ending a giveaway and starting a new one would be ridiculous.

**Comment by bup0441** [comment]
This is a duplicate of #58, and an edit command is unlikely to be added for the immediate future as the bot is being rewritten to support slash commands

**Comment by Yilmaz4** [comment]
Oh I didn't see 58th issue, thanks.
