### ISSUE TITLE
Pulling 'winList' list 

### ISSUE THREAD

**Issue by jgomez4597** [jagrosh/GiveawayBot#137]
Would there be a way for me to pull the winners (winList) as a separate txt file with just the discord name#s?

**Comment by jagrosh** [comment]
In regards to this, a giveaway summary page and json file are available after every giveaway in the rewrite

**Comment by jagrosh** [comment]
As stated, the giveaway summary is available when a giveaway ends; if you have further requests for this summary, please open a fresh issue.
