### ISSUE TITLE
How does rewarding system works there?

### ISSUE THREAD

**Issue by SCARaw** [jagrosh/GiveawayBot#143]
giveaway bot gave me 30 days premium nitro discord and without dodgy links to not-discord how or when do i receive it?

**Comment by jagrosh** [comment]
GiveawayBot does not provide the prizes; you need to contact the host of the giveaway.

**Comment by SCARaw** [comment]
thanks

**Comment by mgdno2024** [comment]
**3USDT**

**Comment by popeda97** [comment]
> 3USDT

**Comment by popeda97** [comment]
#116
