### ISSUE TITLE
Role Requirements

### ISSUE THREAD

**Issue by Jmichaelz** [jagrosh/GiveawayBot#152]
When setting up giveaways, there needs be an option where you can customize what role(s) can join it. 

Example 1
We want to make a giveaway where everyone can NOT join, but only people with the common role can join.

Example 2
We want to make a giveaway where everyone can NOT join, but only people with common, uncommon, and rare roles can join.

**Comment by jagrosh** [comment]
**This is already possible**, just make a channel that is only visible to the users that you want to be able to join (and hidden from everybody else) and hold the giveaway in that channel.

For the sake of consistency for users, it will never be possible to see a giveaway that you cannot enter.
