### ISSUE TITLE
Giveaway bot chose a winner that didn't participate in the giveaway

### ISSUE THREAD

**Issue by Ihoyos96** [jagrosh/GiveawayBot#154]
The bot selected a winner, but that user never reacted to the giveaway bot's post, i.e. never entered the giveaway.

There were only 27 participants, so I was able to comb through the list of who reacted to the giveaway back multiple times trying to figure out if I'd just missed their name. To my surprise that user never reacted to the message. I was able to talk to them and they confirmed they never entered that giveaway.

I don't want to give away user information, but essentially the picture attached shows the giveaway, the 27 participants and 5 winners chosen, but one of them never entered the giveaway but was still selected.

Not sure if this is a one off bug, but I can't imagine it being caught with people running larger giveaways. 

![screenshot (25)](https://user-images.githubusercontent.com/19755314/168173711-7a9bfdae-8dea-4697-9df3-972fb96cbd2c.png)

**Comment by jagrosh** [comment]
The user likely removed their reaction after winning, or their reaction simply isn't showing in your client. The bot can't pick someone that didn't react; it doesn't have any sort of list of users other than what is returned from fetching the list of reactions.

**Comment by Ihoyos96** [comment]
Me and my team double checked the list of who reacted from different computers. The winner in question is part of our team and confirmed they never entered the giveaway.

**Comment by jagrosh** [comment]
It's impossible for GiveawayBot to obtain any user IDs other than those in the reaction list, so they must have entered. Double-check the ID of the winner compared to the member of your team who supposedly didn't enter.

**Comment by Ihoyos96** [comment]
I understand, then it must've been Human Error of some sort on our side. Have a good one.
