### ISSUE TITLE
Multiple Giveaway Admins

### ISSUE THREAD

**Issue by caburum** [jagrosh/GiveawayBot#16]
Is it possible to let muliple people start giveaways?

**Comment by Tqggle** [comment]
Everyone with the permission “Administrator” will be able to create giveaways and manage them. Other than that, I do not believe that there is a role you can give people to manage them. If you have any other questions, hmu. Tqggle#0001

**Comment by jagrosh** [comment]
The Manage Server permission is what you need to create giveaways (or Administrator, which effectively gives it too). If you don't want to give someone that permission, you can create a role called `Giveaways` and give that to whoever should be able to start a giveaway.

**Comment by Tqggle** [comment]
Thanks for contributing! I was wondering this as well, @jagrosh! Thank you very much.
