### ISSUE TITLE
[Feature request] Allow giving permissions to any role without giving them Manage Server permission.

### ISSUE THREAD

**Issue by NotOsho** [jagrosh/GiveawayBot#172]
This could sound much of a gimmick, but having a separate **giveaways** role just in order to host giveaways is absurd. If we could give the permissions to any roles irrespective of the role name, it would look much cleaner in the user roles, since there isn't any extra role required for server moderators for the same. Since no one would want to give server manager perms to all, this configuration could make it much easier for users.

**Comment by jagrosh** [comment]
This is already possible on the interactions rewrite (/g commands) of the bot, which will be entirely replacing the old system soon. Head over to the integration page for the bot and you can specify which roles and in which channels which commands can be used.
![image](https://user-images.githubusercontent.com/12754382/178194013-d921010d-734a-4abf-9f96-795c88c52268.png)
