### ISSUE TITLE
Hey someone stole your bot and modified the code for scams

### ISSUE THREAD

**Issue by Catakang** [jagrosh/GiveawayBot#174]
I was dmed by a bot that told me to join a discord server. It looked like your giveaway bot, but it wasnt verified and upon further inspection, had a different tag. They have been using it to make people join random servers and stuff and it's really scummy. I thought that you should know since you said in your readme.md that it wasn't allowed.
![image](https://user-images.githubusercontent.com/77416223/180584932-bce962ea-92ac-4e94-9269-6744717284bd.png)
![image](https://user-images.githubusercontent.com/77416223/180584935-42367625-25d1-4640-ac8d-3835bfc91f67.png)

**Comment by jagrosh** [comment]
There are tons of these scam bots. Please report them to Discord when you see them, as I can't really do anything about this.
