### ISSUE TITLE
/greroll command always yielding repeat winner on first reroll

### ISSUE THREAD

**Issue by Epignosis21** [jagrosh/GiveawayBot#177]
I noticed since I started using **/greroll ID** instead of **!greroll ID** the first time i do **/greroll id**, it rerolls the original winner. i have to do it a second time to get a new winner. i did not have this issue with **!greroll id**. this has happened to me 100% of the time using the snew slash command on multiple servers with giveways of small size (a few entrants) to large giveways with over 100 entrants.

For further detail i discussed this issue with support user **n11** in the #bot_support. I have attached the screenshots of that conversation for additional reference. 
![image](https://user-images.githubusercontent.com/110763217/183282843-05de042e-5aab-41de-9721-a23b3a1fb953.png)
![image](https://user-images.githubusercontent.com/110763217/183282853-0a57b413-3e8b-43e1-bc5c-74f37a49866f.png)

**Comment by jagrosh** [comment]
The algorithm for selecting a new winner is identical to the previous one, and still random. Based on the number of entrants, it's not all that unlikely to occasionally see repeat winners.

**Comment by Epignosis21** [comment]
I would agree and we used to occasionally see this happen, which of course is to be expected. But should every single **initial** reroll for a giveaway (since moving to slash commands) exhibit this pattern? Including 5 or 6 rerolls on giveaways with entrants in the 100's? It seems statistically impossible to be the case that not a single initial reroll has yielded a non-winner (in probably 10-20 giveaways since ive been noticing this and tracking it across a couple different servers). I just wanted to make sure I point out this is not a "oh this happened a few times" scenario. Hope that helps clarify, if i can provide any further detail let me know. If not i understand, but may report this again in the future if every initial reroll continues to exhibit this behavior, Thanks!:)
