### ISSUE TITLE
Is it possible to favour different roles with a higher chance of winning?

### ISSUE THREAD

**Issue by JamesDonnelly** [jagrosh/GiveawayBot#18]
I'm looking to start offering giveaways to anyone on my Discord server, but I'm wanting donors and Patreon supporters to weigh higher. Is this something GiveawayBot can accomplish?

Ideally I'm wanting something like:

- An entry from a regular user has a weight of 1.
- An entry from anyone with _Role X_ has a weight of 3.
- An entry from anyone with _Role Y_ has a weight of 5.

Thus, _Role X_ would have a 3x higher chance of winning over a regular user, but _Role Y_ would have a 66.67% higher chance of winning over them. Ultimately, anyone in _Role Y_ would win 5 times more often than a regular user.

**Comment by jagrosh** [comment]
This will not be added; every user that enters will always have an equal chance of winning.
