### ISSUE TITLE
add losers in the giveaway list

### ISSUE THREAD

**Issue by WIAIMLM301** [jagrosh/GiveawayBot#180]
i wonder if i can see myself if i lose in discord (directs to webpage instead of showing all of them in a message  cuz its too long,yeas or no,if replied, close issue/ticket, Note: reply with yes/no/i think so/i dont think so,then reason)

**Comment by jagrosh** [comment]
It's not possible to show the giveaway summary within Discord, as the content is often far longer than the maximum allowed characters in a message.
