### ISSUE TITLE
Giveaway help

### ISSUE THREAD

**Issue by TrulyLife420** [jagrosh/GiveawayBot#190]
I am having my whole community complain to me about this and it is also bothering me that I don't even want to do giveaways until it shows who's entered because some people either enter multiple times now or not in at all. I was trying to get in touch with Someone who could help the first guy told me it's not broken and it should work. That was what he said and he said it is what it is. Then the next guy was actually helping me then this Read About Me tells me F**k you in your discord server. I was just trying to get help it's frustrating that when you enter you can't get the owner via ping and you can't privately message him because he has a rule against that!

So hard to get help there only one person was being respectful to me as I am trying to figure out why it's messing up I get told F**k You! By Read About Me!

This is very professional and how staff should be to members looking for help!This is how to be professional these days then I'm not there yet I have some self control with my cussing! I don't tell anyone that I am here to help Fu*k You!

Then trying to get help and you immediately close this so nobody else can see this?

Just as professional as Mr. Read My About Me! Unless that's you anyways??!!

Tell me otherwise

![Screenshot_20220820-153335](https://user-images.githubusercontent.com/111660178/185765007-88ba28a9-2bff-43ec-9f46-0689e74d20d8.png)

**Comment by jagrosh** [comment]
> I don't even want to do giveaways until it shows who's entered because some people either enter multiple times now or not in at all

This is already being tracked, there is no need to continue to mention it again and again. Everything else in your post is related to the Discord server and not the bot.

I've also asked you to stop creating new issues instead of commenting on the ones that already exist. This is extremely disruptive to the issue-tracking here.
