### ISSUE TITLE
Feature Request: Automated Giveaways

### ISSUE THREAD

**Issue by Khuonggg** [jagrosh/GiveawayBot#197]
Let's say that I have a server and I want to give away a custom server role each month. I suggest that there should be a way to configure the bot so the giveaways start automatically one after the other. That would be a really cool feature and it would definitely help create daily/monthly giveaways more precisely so no time would be missed in between each giveaway.

**Comment by R1ggie** [comment]
Scheduling a giveaway is planned in the future - but as of now no date has been placed. 

For now i either suggest starting the next months giveaway a few hours before the other 1 is about toe end.

**Comment by jagrosh** [comment]
This is in essence a duplicate of #96. Fully automated giveaways (infinitely repeating) will probably never happen, but it's possible that one or both of the following would happen:
1. The ability to schedule a giveaway ahead of time
2. The ability to 'repeat' a giveaway, creating a new giveaway that runs for the same duration as one that ended
