### ISSUE TITLE
Same as issue #180 And 198,but unlike issue 180 only ,add losers below text of winners instead And Add Honour message to losers

### ISSUE THREAD

**Issue by WIAIMLM301** [jagrosh/GiveawayBot#199]
unlike winners, losers cannot be typed while creating giveaway, it will automatically appear after max winners+1, 
formula is amount of entrants-winners, also unlike winners, they wont be appeared on list when giveaway ends as issue 180 says it is not possible due to  far max length from discord ,like if there is 5k entrants and 1 winner, then 4999 losers mentioned above would be 25-27 times longer than maximum length of discord message
secondly,i suggested if you lost a giveaway, they should deliver a message to honour you if you lost a giveaway like in issue 198,unlike issue 198,it wont delivery package/voucher if you lose it
for the first one:
Eg:100 entrants in a giveaway
Winners:10
Losers:90
Second one:
like: although you entered nto giveaway,but sadly you lost the giveaway better luck next time!
thats all,btw Note for the second one is the delivered message must be discord giveaway bot via direct messages

Before Reply: i suggest read below
Which suggestion is not possible to add/which suggestion is possible to add (either 1)

**Comment by bup0441** [comment]
Neither of these features will be added.
1. A list of losers would be redundant, as all entrants are already listed in the giveaway summary at the end, and it would not be difficult to extrapolate who lost. Additionally, listing everyone other than the winner(s) as "losers" doesn't seem like a particularly helpful change to anyone involved.
2. A "better luck next time" message seems like a niche addition at best, and furthermore as of August 31st, 2022, GiveawayBot will never send direct messages to users. Mass DMing users is a phenomenal way to get a bot disabled for spam, and for the vast majority of end users, it would only be a nuisance. For the full list of reasons on why GiveawayBot will not be DMing people, jagrosh went into exhaustive detail at the bottom of #198.

**Comment by GodlyFirecracker** [comment]
Reopen issue pls

**Comment by GodlyFirecracker** [comment]
you should reconsider first,btw it is only for the beginning not end,at the end it lists all of them tho,however i personally think adding losers into winners count below is a good idea tho
