### ISSUE TITLE
Blocking roles

### ISSUE THREAD

**Issue by xinitrc-dev** [jagrosh/GiveawayBot#21]
I've read that you don't want any users to be favoured over others who entered the giveaway, what about blocking some from entering it in the first place?
Could you implement something like "Giveaway" role (which allows creating giveaways) but one that will ignore users who reacted to the giveaway that have a certain role? (disabling read messages permission isn't an option)

**Comment by jagrosh** [comment]
To prevent a role from entering a giveaway, simply hide the channel from the role; no configuration is needed on GiveawayBot, as being unable to Read Messages in a channel prevents adding the necessary reaction to enter the giveaway.

**Comment by iam-malc** [comment]
I see this was closed as completed, but I was wondering if I could re-raise it. Reason being, I want to limit a role in this server from entering the giveaway completely. They can see it, but shouldn't be able to participate

**Comment by MichailiK** [comment]
> They can see it, but shouldn't be able to participate

This will never get implemented. See pinned issue #153

**Comment by iam-malc** [comment]
Thanks! I read through and I see and understand
