### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by coleby41** [jagrosh/GiveawayBot#222]
I think there should be eyes only prompt where it confirms that you have entered the giveaway

**Comment by JetCrooked** [comment]
duplicate, see #181

**Comment by Zoddo** [comment]
I'd like to point out that the response in #181 is not accurate. Interaction follow-ups (which are just webhooks) are not bound to the global rate limit, as documented [here](https://discord.com/developers/docs/interactions/receiving-and-responding#endpoints).

So, sending an ephemeral followup shouldn't cause any issue with the global ratelimit (and anyway, even if that ratelimit was applied to followups, GiveawayBot is large enough to request a global ratelimit increase).

**Comment by jagrosh** [comment]
For organization let's keep all relevant information in the same issue

**Comment by atifnimran** [comment]
Ok
