### ISSUE TITLE
Add Required role and blacklisted role

### ISSUE THREAD

**Issue by nerdboyyt** [jagrosh/GiveawayBot#252]
When someone is starting a giveaway there should be an option(optional) that says add required roles
By this i mean the role that people  need to join that specific giveaway

Also add blacklisted role
This is a general one for the specific server
Blacklisted role is a role that if someone has it they cant join any giveaway hosted in that server
In /gsettings there should be an option to add blacklisted role

**Comment by MichailiK** [comment]
This will never get implemented. See pinned issue #153

**Comment by nerdboyyt** [comment]
ok
