### ISSUE TITLE
On `/greroll <giveaway_id>`, display the reward with the winner

### ISSUE THREAD

**Issue by Rylium** [jagrosh/GiveawayBot#256]
Hi there~

On a `/greroll`, the user selected randomly by the bot is not notified about the reward acquired.
The actual message is: <@user> rerolled the giveaway! Congratulations <@user>!
The correct message will be: <@user> rerolled the giveaway for `reward`! Congratulations <@user>!

Hope this will help!

**Comment by zplus11** [comment]
I think this was suggested some time before as well.
That said, you can click on the "redirect" arrow in the reroll announcement message. It takes you to the giveaway being rerolled, so you know what was rerolled.

**Comment by Rylium** [comment]
It was more an UX-feedback, but okay, I'll inform future giveaway winners that this is the way to go, thx :)

**Comment by CallMeKittyKatie** [comment]
Hi

**Comment by MoustafaReda95** [comment]
heloo everyone
