### ISSUE TITLE
Required Roles Feature 

### ISSUE THREAD

**Issue by gg70073** [jagrosh/GiveawayBot#259]
Hello Developer, the Giveaway bot has been around for a long time and users love it.

But it's lacking some very main key features even though it is a bot solely made for **Giveaways**

> The features that the bot lacks are :

> 1. Giveaway Participation Required Roles Setting  : to set a role and members only with that role can participate. 
> 2. Host name edit.

These features are available in a lot other bots but I would prefer them in the giveaway bot as it is created solely for giveaways and is clean.

The feature that I personally love in the bot is that the embed color is editable.

If anything, the setting `to set a role and members only with that role can participate` is extremely necessary. 

Adding these features may not take much time to code 
I hope you care and am concerned and look into this as soon as possible.
Thank you.

**Comment by MichailiK** [comment]
See #153 for reasons why restrictions to Giveaways won’t be implemented.
