### ISSUE TITLE
Multiple Entries via Raffle/Giveaway for specific roles

### ISSUE THREAD

**Issue by Swizz0713** [jagrosh/GiveawayBot#268]
Hello Developer, the Giveaway bot has been around for a long time and users love it.

I have searched everywhere but couldn't find a bot that offered a key feature I've been looking for my community. 

Is there a way (or is this a feature that can be implemented if it doesn't already exist) for users with specific roles to submit multiple entries? For example:
**Role A:** Can react/enter 2 times
**Role B:** Can react/enter 3 times
**Role C:** Can react/enter 4 times
etc.

I believe this would be very helpful especially for artist-centric communities where patrons/members can enter multiple times based on their tiers/roles in the server. I searched the Dashboard and don't think this is something that is currently offered unless I overlooked it.

I'm not a dev, but would adding this feature be something too demanding? I wouldn't even mind if this would be something gated behind patron-only premium users.
Thank you.

**Comment by jagrosh** [comment]
#153
