### ISSUE TITLE
Restrict giveaways to specific roles

### ISSUE THREAD

**Issue by BetterDeadThanZed** [jagrosh/GiveawayBot#269]
I'd love go see the ability to restrict a giveaway to only people with a certain role.

**Comment by MichailiK** [comment]
This won't be added. See #153 for reasons why entry restrictions/modifications will not be added to GiveawayBot.

**Comment by BetterDeadThanZed** [comment]
The idea here is that my players voiced the opinion that they don't all want to be pinged when there's a giveaway (We were pinging everyone that played a specific game), so we created a role that we can ping without disturbing all players of that game. Players can self assign the role in Discord. Limiting giveaways to those in a specific group would encourage players to assign themselves the role. I suppose editing the channel permissions for the giveaway bot so only those with that role can see it would work too since the giveaways are typically just for the one game server, but we could just change it so that role is for all of the games we play. Not the optimal choice though.

**Comment by PixelSmith720** [comment]
You could check out [Sx Bot](https://sxbot.io) as it allows you restrict giveaways to certain roles.
