### ISSUE TITLE
Giveaways with more than 15 winners

### ISSUE THREAD

**Issue by blendiahmetaj1** [jagrosh/GiveawayBot#29]

**Comment by jagrosh** [comment]
Currently giveaways are limited to 15 users, although it should be feasible to increase this; the reasons for limiting it at all are:
- it takes longer (and more processing power) to select more winners (although not a lot)
- the final result message needs to stay within Discord's 2000 character limit

As a workaround until the limit is increased, you can use `!greroll` to select additional winners; there is no limit to the number of times you can reroll a giveaway, and none of the existing winners get overwritten.

**Comment by whalehub** [comment]
@jagrosh Are there any plans to increase the limit anytime soon? We want to create giveaways with over 100 winners regularly.

**Comment by jagrosh** [comment]
There are plans for a way to increase the limits, which will be available soon (hopefully this weekend if I can finish everything up). However, this still won't be near 100, as 100 user mentions don't even fit into a single discord message (~21 characters per mention, plus spaces, the name of the prize, and the base message). Also keep in mind that all the winners need to get edited into the giveaway message, and there is a (slightly higher) character limit there.

I will continue to think about how more winners could be fit, but I don't really think 100 is feasible. Do you have any more information about your use-case?

**Comment by whalehub** [comment]
@jagrosh Thanks for your feedback. I will simply make use of the !greroll feature in that case.

**Comment by blendiahmetaj1** [comment]
we are from a browser game and we want to increase activity in our discord and it is not quite good to reward only 15 players

**Comment by Sanduhr32** [comment]
@blendiahmetaj1 then you may become a patr(e)on or boost our Discord Giveaways server for being rewarded with a benefit above the public limit of 20 giveaways per channel with 20 winners each.
