### ISSUE TITLE
Letting other bots create giveaways

### ISSUE THREAD

**Issue by OliMoose** [jagrosh/GiveawayBot#32]
Could you maybe make it so that other bots can create giveaways/use GiveawayBot's commands? i.e. if a server's members reaches some threshold, my bot starts a giveaway using GiveawayBot like a normal user would.

**Comment by jagrosh** [comment]
Bots controlling other bots is not something that will be added; I'd recommend just building the giveaway functionality into your own bot.

Something that is planned is being able to schedule giveaways; I might consider having alternative triggers for when a giveaway starts, but I don't know when/if that will be added.
