### ISSUE TITLE
Discord link

### ISSUE THREAD

**Issue by TaZePug** [jagrosh/GiveawayBot#41]
Since i have no clue how im suppose to report this any other way 

![2E1617C3-DD95-4C28-88A6-8560BD3C1DFA](https://user-images.githubusercontent.com/53272749/71484120-a4e8fe80-2802-11ea-8693-1298da1a0090.png)

**Comment by jagrosh** [comment]
Which invite link are you trying to use, and from where did you get the link?

**Comment by jagrosh** [comment]
Nevermind, I'm assuming you meant the link on the readme of this repository, which I failed to update when the server was remade... I'll fix that now.

**Comment by TaZePug** [comment]
Also on https://giveawaybot.party/support
