### ISSUE TITLE
How to reroll a giveaway with >1 winners

### ISSUE THREAD

**Issue by andrelkzy** [jagrosh/GiveawayBot#45]
If I make a giveaway for 2 winners, and 1 doesnt claim his prize, how do i reroll for 1 more winner instead of rerolling for the 2 of them?

**Comment by Sanduhr32** [comment]
You reroll multiple times.
Thank's.
In the future please visit jagrosh's Bot server or Giveawaybots support server.

**Comment by andrelkzy** [comment]
> You reroll multiple times.
> Thank's.
> In the future please visit jagrosh's Bot server or Giveawaybots support server.

im sorry, i didnt know about that server, thanks for your help
