### ISSUE TITLE
Offline Winners

### ISSUE THREAD

**Issue by PurpleFlaw** [jagrosh/GiveawayBot#49]
Offline winners show up as ID numbers instead of a Username which forces us to reroll because you can’t ping an ID #

**Comment by Sanduhr32** [comment]
Are you sure that it is not Discord Lazy Loading or that they didn't leave your Discord?

**Comment by DanHarrin** [comment]
You can @mention an ID with `<@ID_HERE>`.

**Comment by PurpleFlaw** [comment]
Yes. We are sure that when the winners are offline that it doesn’t show
their username just their number tag. Because you can mention their ids in
dms and it works fine even if they aren’t in the server or if the dm is not
towards them. We mentioned their id in the server and they were
offline(they were still in the server tho)

**Comment by jagrosh** [comment]
This is not something that can be changed on the bot's end; the Discord client displays user mentions as `<@ID>` when the user is not cached, so the difference is purely a factor of how the Discord client works, not how the bot works.
