### ISSUE TITLE
No contents once giveaway is created

### ISSUE THREAD

**Issue by xyeLz** [jagrosh/GiveawayBot#5]
Hi there,

I've added your bot to my server but when I create the giveaway, it creates it in the channel I selected but doesn't have any contents (ie: doesn't tell the user to react, doesn't say when it will end, etc).

**Comment by tandpfun** [comment]
Hmmm... try giving it owner permissions and maybe all permissions to test it out. It may need to be able to send tts messages.

**Comment by jagrosh** [comment]
It sounds like you don't have Link Preview enabled. Try going to your Text & Images settings and enabling this:
![LinkPreview](https://i.imgur.com/IBBsRgn.png)

**Comment by tandpfun** [comment]
oops! Wrong setting.

**Comment by jagrosh** [comment]
If you already have that setting enabled, then it could be a permissions issue, although the bot does check for the needed permissions. If after enabling link preview it still doesn't work, try giving the bot the Administrator permission and re-creating the giveaway.
