### ISSUE TITLE
Suggestion: Only allow users with a specific role to participate/win a giveaway

### ISSUE THREAD

**Issue by VasinklingGR** [jagrosh/GiveawayBot#50]
Example: If the user reacts and doesn't have the `lvl 5` role then don't allow them to participate but if another user reacts and has the `lvl 5 `role then allow that user to participate in the giveaway. The role can be chosen while creating a new giveaway

This will be a nice feature to have cause it will prevent from having to reroll giveaways until a person with the correct requirements is found

**Comment by Sanduhr32** [comment]
You have to configure your discord channels this way and do special announcements there.

**Comment by VasinklingGR** [comment]
This is a way to do it but that's a lot of extra work for server admins to do. It's easier to use 1 channel for everything where all members will be able to see (and meaby encourage members that don't have the role to get it) then setting up channels for every special role you want to start a giveaway to
Most bots I test that includes giveaways usually have this built in so I thought why not include it in giveaway bot 
  On Wed, Aug 5, 2020 at 1:17 AM, M R S E<notifications@github.com> wrote:   


You have to configure your discord channels this way and do special announcements there.

**Comment by Sanduhr32** [comment]
This feature is sadly not worth to be done, due to upscale our database for everyone and possibly decreasing our performance.

**Comment by VasinklingGR** [comment]
Damn that sucks but thanks for considering this to be added. This will help me and alot of discord servers I'm in that host giveaways.
