### ISSUE TITLE
Allowing specific roles to create giveaways

### ISSUE THREAD

**Issue by S-i-r** [jagrosh/GiveawayBot#52]
Many people wish to create a role called "Giveaways" people can subscribe to. I'd recommend looking for something like "Giveaways Admin" or something of that nature. Otherwise it's incredibly easy for people to accidentally give the "Giveaways" role to everyone.

**Comment by jagrosh** [comment]
This can't be directly changed simply because of the existing scale of the bot. If you want a role to ping for giveaways, consider naming it "Giveaway Notification" or "Giveaways 🎉".

In the future, it may be possible to _change_ which role is used to manage giveaways, but the default behavior of looking for a role called "Giveaways" will likely always be the case.

**Comment by jagrosh** [comment]
A small update on this; the upcoming rewrite of the bot will likely address this in some capacity.

**Comment by JetCrooked** [comment]
> A small update on this; the upcoming rewrite of the bot will likely address this in some capacity.

> As of the slash commands rewrite:
> 
> 1. Like existing functionality, users must have the Manage Server permission or the giveaway role to manage giveaways
> 2. If no giveaway role has been set for a server, GiveawayBot will look for a role called "Giveaways" (case-insensitive) and set it to the giveaway role
> 3. The giveaway role can be changed by users with the Manage Server permission via `/gsettings set role @rolename`

another small update: the concept of a giveaways role has now been made obsolete by discord's new command permissions system, which GiveawayBot will exclusively use instead of a giveaway manager role

**Comment by jagrosh** [comment]
This is fully controlled via the Integrations page (Server Settings > Integrations > GiveawayBot) and can be customized per-role and per-channel.
