### ISSUE TITLE
Suggestion | Role limited giveaways

### ISSUE THREAD

**Issue by The0Show** [jagrosh/GiveawayBot#53]
It would be cool to be able to limit a giveaway to certain roles (like @Level 10). I know Santa Wumpus already has this, but it sends you 2 discord invite links once you join or get denied to join, so I don't use it.

**Comment by jagrosh** [comment]
You can already do this; simply make a private channel that only your designated roles can see and hold your giveaway there.

In general, to preserve use experience and consistency, if they can see a giveaway, they can enter it, and they have the same chance to win as everyone else who enters.
