### ISSUE TITLE
Bot not declaring a winner.

### ISSUE THREAD

**Issue by rudigo** [jagrosh/GiveawayBot#65]
The giveaway of my server is bugged. The bot doesn't declare a winner despite of the giveaway end time being passed more than 30 minutes ago.

I would like to know what to do, since this is the second time I'm trying to make a giveaway. This has been very embarrassing for my server...

![image](https://user-images.githubusercontent.com/13781732/103464209-c8a22700-4d29-11eb-892f-bd285a4e6290.png)

**Comment by jagrosh** [comment]
[As you can see here](https://discordstatus.com/), Discord recent suffered an API lag spike, which could cause giveaways to be delayed, or possibly not end at all if Discord consumes the request and does nothing with it. When this happens, there is nothing that can be done on the bot's side to fix this. The only solution is to wait until after the lag subsides, and then either manually end or reroll the giveaway.
