### ISSUE TITLE
State Number of Participants When Giveaway Ends

### ISSUE THREAD

**Issue by Deantwo** [jagrosh/GiveawayBot#74]
![image](https://user-images.githubusercontent.com/2676134/113876573-26765d00-97b8-11eb-9737-e99fb2739cbc.png)

Currently it does not show how many participants were in the giveaway when the giveaway ended. This is a minor issue because people are still able to add/remove reaction emojis to the giveaway message after it ended.

I simply suggest that the message say the number of participants in the message alongside who the winner was.

**Comment by Deantwo** [comment]
Sounds good to me.

**Comment by jagrosh** [comment]
This is something that I'll be adding when I overhaul the ending message

**Comment by jagrosh** [comment]
This has existed for a while now
