### ISSUE TITLE
[FEATURE REQUEST]Multiple Role Restriction

### ISSUE THREAD

**Issue by itoffie** [jagrosh/GiveawayBot#75]
just like Santa Lunar bot it has multiple role restrictions on giveaways but needs premium for it to work. i hope you can integrate it here and make it free :+1:

**Comment by jagrosh** [comment]
You can already restrict a giveaway to roles by making the channel that the giveaway is visible in only visible to people with those roles. A user must be able to see a giveaway to enter it, so Discord's Read Messages permission is already suitable for this use-case.

Conversely, there are no plans to make it possible for a user to see a giveaway and not be able to enter it. This would be confusing and inconsistent for users.
