### ISSUE TITLE
Add requirement options to setup while creating giveaways.

### ISSUE THREAD

**Issue by wellskilled** [jagrosh/GiveawayBot#79]
Hi. I think requirement options like: role, number of messages sent and other ones would be nice to see in giveaway bot. If u want it could be added for premium users only but it doesn't have to be.

**Comment by Sanduhr32** [comment]
We have clarified that we will always stick to our current "restrictions" and will never add custom restrictions required for entering a giveaway.
If you can see a giveaway you can enter and are eligible to win it.
