### ISSUE TITLE
[Issue] Remove setup messages when giveaway has been created

### ISSUE THREAD

**Issue by maxlehot1234** [jagrosh/GiveawayBot#8]
Hi, How I can remove all setup message automatically when the giveaway start?

If I can't automatically, it is something you need to add to make the bot AMAZING ;)

If I can, let me know how.

Thanks again and nice job on this

**Comment by jagrosh** [comment]
When using `!gcreate`, I'd recommend using the setup commands in a private channel. When using `!gstart`, the bot will automatically delete the message if it has sufficient permissions.

**Comment by maxlehot1234** [comment]
I give all permissions and the bot doesn't remove setup messages. I will try the private channel options ;)
Thanks for the tip
dimanche 18 mars 2018 16:13 -0400 de notifications@github.com  <notifications@github.com>:

**Comment by jagrosh** [comment]
It does remove the single setup message when using `!gstart` if it has perms. It does not remove the multiple-message setup when doing `!gcreate`
