### ISSUE TITLE
"Claim" feature

### ISSUE THREAD

**Issue by ByemaxTheGamer** [jagrosh/GiveawayBot#81]
A new command: "!gclaim [id] @user"
Whenever used with the id of a giveaway and pinging a user, it will unreact the user everytime they react to said giveaway unless the command is used on them again

**Comment by Sanduhr32** [comment]
This kind of breaks our philosophy of "See it? Enter it!".
We believe it's not intuitive to not be able to enter a giveaway which you can see.
Also un-reacting automatically might cause API spam & hurt our performance.

**Comment by jagrosh** [comment]
This seems like a direct extension of #80; when someone wins, you'd want to remove them from the existing pool and also prevent them from entering that pool again. I'm going to close this issue, as I think everything here is implied by the other one.
