### ISSUE TITLE
command to view winners

### ISSUE THREAD

**Issue by BeeFreeHere** [jagrosh/GiveawayBot#87]
I am missing a command to view list of winners!

**Comment by Sanduhr32** [comment]
The original giveaway message and the ending message list all initial winners of a giveaway.
You manually have to keep track of them when you reroll later.

**Comment by BeeFreeHere** [comment]
Hmmmm I only see a winner when I reroll.

There is no end screen with winners

**Comment by Sanduhr32** [comment]
> Hmmmm I only see a winner when I reroll.
> 
> There is no end screen with winners

This is intentional. You only reroll one winner at a time.
