### ISSUE TITLE
Command !gstart extra parameter request to draw unique winners

### ISSUE THREAD

**Issue by BeeFreeHere** [jagrosh/GiveawayBot#88]
Drawing winners can in a lottery with more then one winner can draw same winner multiple times
Possible fix could be to have geroll get 3 winners in one roll instead of one winner

!gstart 14d 3w price1 / price2 / price3
!greroll

**Comment by Sanduhr32** [comment]
Giveawaybot is not designed for running a lottery. You would have to manually do 3 giveaways or one and depending on who has been drawn and listed first to get that prize.

**Comment by BeeFreeHere** [comment]
Well when I open with 3w it's a bit odd that I get trice the same winner (using !greroll) where in "test" i had 2 contenders.

**Comment by Sanduhr32** [comment]
The bot does not pick the same winner several times if more than one winners are possible when ending the giveaway.
