### ISSUE TITLE
Bot Does not show on my server

### ISSUE THREAD

**Issue by AtharvGaming** [jagrosh/GiveawayBot#94]
Bot Does not show on my server

**Comment by bup0441** [comment]
This sounds like a basic permissions issue or like something kicked the bot; check your audit logs to see if anything or anyone kicked/banned it, and check your Roles section in server settings. If GiveawayBot's integration role is there you need to give it permissions to see your server.
Issues like this would be better brought up in GiveawayBot's support server, discord.gg/giveawaybot.
