### ISSUE TITLE
[Feature Request] - Only allow users who have sent X messages in the last X hours/days/week to quality for an entrance to the raffle 

### ISSUE THREAD

**Issue by DarkDownloader** [jagrosh/GiveawayBot#95]
Title - I love Giveaways, but I hate people who are inactive in my Discord just so they can try to win a Giveaway. Would be an awesome feature if we could set parameters so people must remain active in some fashion to enter, also maybe a message that informs them they are not active enough to enter?

**Comment by jagrosh** [comment]
For the sake of consistency of users, GiveawayBot will not break the rule of "if you can see a giveaway, you can enter it." Therefore, this feature will not be added to GiveawayBot.

However, you could still attain this feature by using some other bot that tracks activity to assign a role to qualified users, and then host the giveaway in a channel that only users with that role can see. I don't know of bots that have this exact feature off the top of my head, but I'm sure that some sort of role-for-activity bots exist out there somewhere; maybe check Discord Bots: https://discord.bots.gg
