### ISSUE TITLE
[Feature request] Adding text

### ISSUE THREAD

**Issue by KevinConsen** [jagrosh/GiveawayBot#98]
Would be lovely to be able to enter extra text other than a prize title. Such as rules or requirements to collect the prize etc.

**Comment by jagrosh** [comment]
I know this was briefly discussed in various channels in Discord, but to clarify, this is specifically referring to add just normal text to the content of a giveaway message; GiveawayBot will always function the same in terms of picking a winner: everyone who is able to enter (by being able to see the channel) has an equal chance to win.

**Comment by jagrosh** [comment]
Giveaways created via `/gcreate` support a description field where you can include any custom text.
