### ISSUE TITLE
[Feature request] Select winner from a post in a specific channel

### ISSUE THREAD

**Issue by KevinConsen** [jagrosh/GiveawayBot#99]
Would be awesome to be able to open a channel, let people post a photo entry or text entry and have the bot select a winner from the posts

**Comment by jagrosh** [comment]
This almost certainly won't be happening, as the rewrite of the bot only uses interactions, which doesn't include posting to a channel (so the bot won't actually receive any messages that are sent).

**Comment by jagrosh** [comment]
Closing this as GiveawayBot will no longer connect to the gateway after the slash commands rewrite is fully live, making any kind of message-style-event-based entry impossible
